### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by shubhpy** [np1/pafy#77]
Actually
i was using gdata.youtube.com/api/feeds/videos/video_id to get video title from its id.
It was working very well but today it isn't working and showing that "connection to target machine is actively refused "
From somewhere i found that pafy can be used for this.
but same error no success

code : 
import pafy
url = "https://www.youtube.com/watch?v=nX30Sgchc20"
video = pafy.new(url)
print video.title

Error:
Traceback (most recent call last):
  File "UsingThirdPartylink.py", line 4, in <module>
    video = pafy.new(url)
  File "C:\Python27\lib\site-packages\pafy\pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "C:\Python27\lib\site-packages\pafy\pafy.py", line 1047, in __init__
    self.fetch_basic()
  File "C:\Python27\lib\site-packages\pafy\pafy.py", line 1062, in fetch_basic
    self._fetch_basic()
  File "C:\Python27\lib\site-packages\pafy\pafy.py", line 1096, in _fetch_basic
    allinfo = get_video_info(self.videoid, newurl=info_url)
  File "C:\Python27\lib\site-packages\pafy\pafy.py", line 144, in get_video_info
    info = fetch_decode(url)  # bytes
  File "C:\Python27\lib\site-packages\pafy\pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>

**Comment by ids1024** [comment]
If you are having the same problem using the api directly, this is not a bug in pafy. You can try pafy's `develop` branch to see if it is working with gdata v3, the newer version of youtube's api that pafy has just been ported to use.
