### ISSUE TITLE
Error obtaining video information: HTTP Error 402: Payment Required

### ISSUE THREAD

**Issue by Nekmo** [np1/pafy#98]
This is working on a public server. I think Google has registered my IP and Google requires authentication.

I need to know how I login to the API.

**Comment by lol768** [comment]
If you have your own API key, you can set it: https://github.com/np1/pafy/blob/develop/pafy/pafy.py#L1616

**Comment by ids1024** [comment]
What video? That message suggests it is a video that costs money to view (youtube has some of those).

**Comment by kais58** [comment]
Are you using OVH?

I think I'm seeing the same issue, even with my own API key:

>>> pafy.set_api_key('<server applications key here>')
>>> pafy.new('KG_mbCgp_zU')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 145, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 1076, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 1091, in fetch_basic
    self._fetch_basic()
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 1126, in _fetch_basic
    allinfo = get_video_info(self.videoid, newurl=info_url)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 152, in get_video_info
    info = fetch_decode(url)  # bytes
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 97, in fetch_decode
    raise e
urllib2.HTTPError: HTTP Error 402: Payment Required

**Comment by Nekmo** [comment]
Yes, I'm usign OVH.


Un cordial saludo:
-- Nekmo.

Sitio web: http://nekmo.com
Dirección de contacto: contacto@nekmo.com
XMPP/Jabber: contacto@nekmo.com
Google+: Nekmo Com

2015-06-11 18:48 GMT+02:00 Callum Massey <notifications@github.com>:

**Comment by kais58** [comment]
Figures, I've had 3 different IPs off them now, all get the same, is there anything we can do about it?

**Comment by Nekmo** [comment]
I just needed Pafy to get information about videos. My solution has been to
use the Google API. It has worked well. With my own Google key the result
with Pafy was the same (not works, error 402).


Un cordial saludo:
-- Nekmo.

Sitio web: http://nekmo.com
Dirección de contacto: contacto@nekmo.com
XMPP/Jabber: contacto@nekmo.com
Google+: Nekmo Com

2015-06-11 19:48 GMT+02:00 Callum Massey <notifications@github.com>:

**Comment by lol768** [comment]
@Nekmo I'm curious, does `curl -i -A "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36" --referer "https://youtube.com/watch?v=KG_mbCgp_zU" http://www.youtube.com/get_video_info\?video_id\=KG_mbCgp_zU\&asv\=3\&el\=detailpage\&hl\=en_US` give the same response for you?

**Comment by kais58** [comment]
full response from the above command below:

HTTP/1.1 402 Payment Required
Date: Thu, 11 Jun 2015 19:07:00 GMT
Server: gwiseguy/2.0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
Expires: Tue, 27 Apr 1971 19:44:06 EST
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Set-Cookie: VISITOR_INFO1_LIVE=F9xG11qCrv8; path=/; domain=.youtube.com; expires=Wed, 10-Feb-2016 07:00:00 GMT; httponly
Set-Cookie: YSC=f67JeJVrNOk; path=/; domain=.youtube.com; httponly
Alternate-Protocol: 80:quic,p=0

**Comment by ids1024** [comment]
Based on that output, it seems to have nothing to do with pafy. Google must be blocking your IP for some reason.

**Comment by lol768** [comment]
@ids1024 Is there any info we get from that endpoint which gData3 wouldn't be able to give us?

**Comment by Nekmo** [comment]
@lol768 

    [nekmo@shizune ~]$ curl -i -A "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36" --referer "https://youtube.com/watch?v=KG_mbCgp_zU" http://www.youtube.com/get_video_info\?video_id\=KG_mbCgp_zU\&asv\=3\&el\=detailpage\&hl\=en_US
    HTTP/1.1 402 Payment Required
    Date: Fri, 12 Jun 2015 16:48:00 GMT
    Server: gwiseguy/2.0
    X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
    P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
    Cache-Control: no-cache
    Expires: Tue, 27 Apr 1971 19:44:06 EST
    X-Frame-Options: SAMEORIGIN
    Content-Type: text/html; charset=utf-8
    X-Content-Type-Options: nosniff
    Content-Length: 0
    Set-Cookie: YSC=ku_lohmMTVU; path=/; domain=.youtube.com; httponly
    Set-Cookie: VISITOR_INFO1_LIVE=01onZKSxizI; path=/; domain=.youtube.com; expires=Thu, 11-Feb-2016 04:41:00 GMT; httponly
    Alternate-Protocol: 80:quic,p=0

**Comment by Nekmo** [comment]
@ids1024 I'm usign now Google Youtube API in my server without problems. Only Pafy fails.

**Comment by ids1024** [comment]
@lol768 Good question. It looks like `get_video_info` is used to get the stream urls, which are not available in gdata.

@Nekmo Does youtube-dl work?

**Comment by lol768** [comment]
@ids1024 Not too surprised about the stream URLs missing from the official API. I imagine everyone experiencing this would be *unable* to play videos through the web interface from the server's connection, too? (I'm assuming, as you suggested, that they're IP blocked and that the official web interface still uses `get_video_info`).

**Comment by Dav1dde** [comment]
I just ran into the same problem, really annoying .. According to [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error) you're required to enter a captcha. youtube-dl gives me `WARNING: unable to set language: HTTP Error 429: Too Many Requests`.

**Comment by ids1024** [comment]
As @Dav1dde said, there is a captcha that has to be solved.

A web search suggests that opening a browser, going to the youtube website, and solving the captcha should fix this. This obviously is problematic on many hosting setups, but perhaps it helps someone.

**Comment by lol768** [comment]
Interesting status code to use when a CAPTCHA is required.

**Comment by ids1024** [comment]
Apparently 402 errors are never used (the payment system they are meant for has never been implemented), so YouTube repurposed it to their own use.
